name: matrix_test
on:
  workflow_dispatch:
jobs:
  ReuseableMatrixJobForDeployment:
    strategy:
      matrix:
        target: [dev, stage, prod]
    uses: vinodduri/learn-github-actions/.github/workflows/main.yml
    with:
      target: ${{ matrix.target }}
